- name: Install Java 
  package: 
    name: java 
    state: installed 

- name: Add Application User 
  user:
    name: "{{APPUSER}}"
    comment: "Application User"

- name: Download and extract tomcat 
  unarchive:
    src: "{{TOMCAT_URL}}"
    dest: "{{APPUSERHOME}}"
    remote_src: yes
  become_user: "{{APPUSER}}"

- name: Find old directories 
  find: 
    paths: "{{TOMCATDIR}}/webapps"
    file_type: any
  register: out 

- name: Remove the old webapps 
  file:
    path: "{{item.path}}"
    state: absent 
  loop: "{{out.files}}"

- name: Download WAR file 
  get_url:
    url: "{{WAR_URL}}"
    dest: "{{TOMCATDIR}}/webapps/student.war"
  become_user: "{{APPUSER}}"

- name: Download JDBC Jar file 
  get_url:
    url: "{{JAR_URL}}"
    dest: "{{TOMCATDIR}}/lib/mysql-connector.jar"
  become_user: "{{APPUSER}}"

- name: Copy context.xml 
  template: 
    src: context.xml 
    dest: "{{TOMCATDIR}}/conf/context.xml"
  become_user: "{{APPUSER}}"
  
- name: Update tomcat init script 
  template:
    src: studentapp-init
    dest: /etc/init.d/tomcat 
    mode: 0755
  
- name: Reload systemctld 
  shell: systemctl daemon-reload 

- name: Start tomcat service 
  service:
    name: tomcat 
    state: started 
    enabled: yes 

- name: Stop API Service 
  service:
    name: studentapi 
    state: stopped 
  ignore_errors: yes 

- name: Remove API directory 
  file:
    path: "{{APPUSERHOME}}"
    state: absent 

- name: Create api directory 
  file:
    path: "{{APPUSERHOME}}/api"
    state: directory 
  become_user: "{{APPUSER}}"

- name: Download API war 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/studentapi.war
    dest: "{{APPUSERHOME}}/api/studentapi.war"
  become_user: "{{APPUSER}}"

- name: Download API Service 
  get_url:
    url: https://s3-us-west-2.amazonaws.com/studentapi-cit/studentapi-init
    dest: /etc/init.d/studentapi 
    mode: 0755

- name: Reload Daemon 
  shell: systemctl daemon-reload

- name: Start API Service 
  service:
    name: studentapi 
    state: started 